`commitlint` project setup
terminal-nerds/terminal-nerd pull request #29
Opened 2021-08-20 10:39 UTC by xeho91

TBA...

2021-08-20 21:04 UTC, lax0248917 commented
Ok so....I pushed a commit with the new config and github actions. And the Github Action Check ran the lint on commit messages, and passed. Does that mean its working lol??

2021-08-21 02:43 UTC, xeho91 commented
> Ok so....I pushed a commit with the new config and github actions. And the Github Action Check ran the lint on commit messages, and passed. Does that mean its working lol??

Yes! Congratulations! Please add it to your resume now!!! :)

2021-08-21 02:56 UTC, xeho91 commented on .github/workflows/commitlint.yaml
> +on: [pull_request]
Please include `push` as well

2021-08-21 02:56 UTC, xeho91 commented on .github/workflows/commitlint.yaml
> +                  helpURL: https://github.com/terminal-nerds/terminal-nerd/wiki/%F0%9F%92%8C-Git-commits-convention
This is a nice one to link our Git commits convention! Awesome!

2021-08-21 02:56 UTC, xeho91 commented on .github/workflows/commitlint.yaml
> +            - uses: wagoid/commitlint-github-action@v4
Can you add `name` here, with a value like `Checking the commit message with commitlint`?

2021-08-21 02:56 UTC, xeho91 commented on package.json
> +		"lint:commit": "commitlint"
I'm missing args, flags being passed here, such as: `--from ... --to ...`

2021-08-21 02:56 UTC, xeho91 commented on .github/workflows/commitlint.yaml
> +# should run on all branches in my opinion
Good point. :+1: 

As far I know, if you'll include the `main` and `develop` branches, then it should run on all the Pull Requests onto `develop` branch. So, there's no need to specify more branches than these two. I believe.

2021-08-21 02:56 UTC, xeho91 commented on .commitlintrc.js
> +		},
Isn't this for the `cz-commitizen`? We're not using it, since we have `gacp` instead.

Initially I wanted to use `@commitlint/cz-commitlint`, but configuring all the prompt messages for **Conventional Commits** and **Gitmoji** would be a really tedious job. Hence why - `gacp`.

2021-08-21 02:59 UTC, xeho91 commented on .github/workflows/commitlint.yaml
> +name: Lint Commit Messages
There should be: `Continous Integration`, because we're going to append more files to this one workflow. Such as merging the existing one for Prettier.

2021-08-21 03:24 UTC, xeho91 commented on .github/workflows/commitlint.yaml
> +on: [pull_request]
Nevermind. We discussed it on Discord. :+1:

2021-08-21 03:41 UTC, CED-zking commented on .github/workflows/commitlint.yaml
> +name: Lint Commit Messages
Changed name to Continuous Integration

2021-08-21 03:41 UTC, CED-zking commented on .github/workflows/commitlint.yaml
> +# should run on all branches in my opinion
Removed comments as we have agreed that the default branches will suffice

2021-08-21 03:42 UTC, lax0248917 commented on .github/workflows/commitlint.yaml
> +name: Lint Commit Messages
Changed name to match other workfkiws that will be in place.

2021-08-21 03:42 UTC, lax0248917 commented on .github/workflows/commitlint.yaml
> +# should run on all branches in my opinion
removed comment lines, as we will be using the default branches

2021-08-21 03:43 UTC, lax0248917 commented on .github/workflows/commitlint.yaml
> +            - uses: wagoid/commitlint-github-action@v4
Changed naming to better describe the job

2021-08-21 03:51 UTC, lax0248917 commented on .github/workflows/commitlint.yaml
> +on: [pull_request]
Ater testing we agreed that this only needs to run on a Pull Request. We don't allow direct pushes to branches.

2021-08-21 15:42 UTC, lax0248917 commented on package.json
> +		"lint:commit": "commitlint"
This one has me a little confused. Not sure how to pass args to this, or which ones we should use. I assume this is so that if someone wants to run commitlint locally they can run this script, but it's expecting an input and I'm not sure what to pass in.

2021-08-21 16:16 UTC, lax0248917 commented on .commitlintrc.js
> +		},
From what I can tell this is the commitlint conventional-config. Which matches up with gacp. If I understand correctly it is against this config file that commitlint validates messages. Our CI, it points to this config file to validate commit messages when pushed to a PR.

2021-08-21 19:35 UTC, mariushilleke requested changes
Finished the review, thanks @xeho91 and @lax0248917 for bringing that up, did not know that before, seems to be really cool.

2021-08-21 19:35 UTC, mariushilleke commented on .github/workflows/commitlint.yaml
> +# do we need to specify what branches?
Should we keep those comments? Agree with @lax0248917 that we could apply it for all branches, therefore would delete those comments.

2021-08-21 19:35 UTC, mariushilleke commented on .github/workflows/commitlint.yaml
> +                  firstParent: true
Do we need to add `firstParent` and `token` since the values seem to be the default ones:
https://github.com/wagoid/commitlint-github-action

2021-08-22 03:29 UTC, xeho91 commented on .github/workflows/commitlint.yaml
> +                  firstParent: true
Good point.

Defaults values may change with the new releases _(from their side)_.
I would prefer to avoid the surprise of unexpected behaviour. Hence why, just in case, define those settings, so we can be sure this doesn't change, unless WE want it to. Not when the author of this action wants to.

2021-08-22 03:37 UTC, xeho91 commented on .commitlintrc.js
> +		},
You could use: https://www.npmjs.com/package/@commitlint/config-conventional
to extend it. :)

As far I can tell, it will allow **gitmoji** to be inside the commit message title.

2021-08-22 04:34 UTC, xeho91 commented on package.json
> +		"lint:commit": "commitlint"
![image](https://user-images.githubusercontent.com/18627568/130342383-ec295b31-a5d1-4107-8365-a9ec68b05ec5.png)

We can replace with `commitlint --verbose --from develop --to HEAD`
Full args explanations: https://commitlint.js.org/#/reference-cli

2021-08-22 17:43 UTC, lax0248917 commented on package.json
> +		"lint:commit": "commitlint"
Do these args need to be added to the script in package.json then? So that when someone runs `pnpm lint:commit` it automatically runs `commitlint --verbose --from develop --to HEAD`?

2021-08-22 17:47 UTC, lax0248917 reviewed
I guess you can disregard my comments, as it looks @xeho91 already made the necessary changes that were mentioned throughout the code review.

2021-08-23 00:27 UTC, xeho91 commented on package.json
> +		"lint:commit": "commitlint"
> Do these args need to be added to the script in package.json then? So that when someone runs `pnpm lint:commit` it automatically runs `commitlint --verbose --from develop --to HEAD`?

Exactly, yes. `pnpm lint:commits` is kind of an _alias_ for this entire command: `./node_modules/bin/commitlint --verbose --from develop --to HEAD`.

2021-08-23 18:09 UTC, lax0248917 commented on .github/workflows/commitlint.yaml
> +name: Lint Commit Messages
Due to changeover for branch this was reverted back to original name. Changing to reflect correct name for workflow as "Continuous Integration"

2021-08-25 02:07 UTC, lax0248917 commented
@xeho91 When you get a chance can you look at this configuration. I am worried its not correct, when I pushed the commit, the CI didn't run.

2021-08-25 15:03 UTC, merged